[package]
name = "suite"
version = "0.1.0"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]
edition = "2018"
default-run = "main"

[[bin]]
name = "versions"
path = "src/versions.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
chrono = "0.4.10"
regex = "1.3.4"
itertools = "0.8.2"
clap = "2.33.0"
serde_json = "1.0.46"
plotters = "0.2.12"
