[package]
name = "simple-web-server"
version = "0.0.2"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.3.9"
lazy_static = "1.4.0"
hyper = "0.13.6"
tokio = { version = "0.2.21", features = ["full"] }
