[package]
name = "warp"
version = "0.1.0"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.21", features = ["macros"] }
warp = "0.2.3"
